name: Deploy ke Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e  # Stop execution if any command fails
            cd chatbot

            # Simpan commit saat ini sebelum pull
            PREV_COMMIT=$(git rev-parse HEAD)

            # Tarik update terbaru
            git pull origin main || { echo "Git pull failed"; exit 1; }

            # Install dependencies
            pnpm install

            # Build aplikasi, rollback jika gagal
            if (cd apps/web && pnpm build) && (cd apps/server && pnpm build); then
              echo "Build berhasil!"
            else
              echo "Build gagal! Rollback ke commit sebelumnya..."
              git reset --hard $PREV_COMMIT
              pm2 restart server
              exit 1
            fi

            # Restart aplikasi setelah sukses
            pm2 restart server
